from diffusion_webui.diffusion_models.controlnet.controlnet_canny import StableDiffusionControlNetCannyGenerator
from diffusion_webui.diffusion_models.controlnet.controlnet_depth import StableDiffusionControlNetDepthGenerator
from diffusion_webui.diffusion_models.controlnet.controlnet_hed import StableDiffusionControlNetHEDGenerator
from diffusion_webui.diffusion_models.controlnet.controlnet_mlsd import StableDiffusionControlNetMLSDGenerator
from diffusion_webui.diffusion_models.controlnet.controlnet_normal import StableDiffusionControlNetNormalGenerator
from diffusion_webui.diffusion_models.controlnet.controlnet_pose import StableDiffusionControlNetPoseGenerator
from diffusion_webui.diffusion_models.controlnet.controlnet_scribble import StableDiffusionControlNetScribbleGenerator
from diffusion_webui.diffusion_models.controlnet.controlnet_seg import StableDiffusionControlNetSegGenerator
